config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#          root GET    /                             pages#home
#         users POST   /users(.:format)              users#create
#      new_user GET    /users/new(.:format)          users#new
#         login GET    /login(.:format)              session#new
#               POST   /login(.:format)              session#create
#               DELETE /login(.:format)              session#destroy
#     calendars GET    /calendars(.:format)          calendars#index
#               POST   /calendars(.:format)          calendars#create
#  new_calendar GET    /calendars/new(.:format)      calendars#new
# edit_calendar GET    /calendars/:id/edit(.:format) calendars#edit
#      calendar GET    /calendars/:id(.:format)      calendars#show
#               PATCH  /calendars/:id(.:format)      calendars#update
#               PUT    /calendars/:id(.:format)      calendars#update
#               DELETE /calendars/:id(.:format)      calendars#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new' # Sign in form
  post '/login' => 'session#create' # Sign in action
  delete '/login' => 'session#destroy' # Sign out

  get '/calendars/matches' => 'calendars#matches'
  resources :calendars

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
# == Schema Information
#
# Table name: calendars
#
#  id             :integer          not null, primary key
#  location       :text
#  arrival_date   :date
#  departure_date :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Calendar < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :destination, :optional => true

  def matches
    Calendar.where('arrival_date >= ?', arrival_date).
      where('departure_date <= ?', departure_date).
      where(:destination_id => destination_id).
      where.not(:user_id => user_id)
  end
end

app/models/destination.rb
# == Schema Information
#
# Table name: destinations
#
#  id         :integer          not null, primary key
#  name       :text
#  country    :text
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Destination < ApplicationRecord
  has_many :calendars

  geocoded_by :name
  after_validation :geocode
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class User < ApplicationRecord
  has_secure_password
  has_many :calendars

  validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present? # This prevents horrors if you reseed.
    end
  end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def new
    @calendar = Calendar.new
  end

def show
  @calendar = Calendar.find params[:id]
end

def matches
end

def create
  @calendar = Calendar.new calendar_params
  @calendar.save
  @current_user.calendars << @calendar
  redirect_to @calendar
end

private
  def calendar_params
    params.require(:calendar).permit(:destination_id, :arrival_date, :departure_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end


def create
  @user = User.find_by :email => params[:email]
  if @user.present? && @user.authenticate(params[:password])
    session[:user_id] = @user.id
    redirect_to root_path
  else
    flash[:error] = "Invalid email or password"
    redirect_to login_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
      if @user.save
        redirect_to root_path
      else
        render :new
      end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/new.html.erb
<h1>New Trip</h1>

<%= form_for @calendar do |f| %>

  <div class="container">
    <div id="column1">

  <div class="form-group">
    <%= f.label :destination_id %>
    <%= f.select :destination_id, Destination.pluck(:name, :id), :include_blank => true %>
  </div>

  <div class="form-group">
    <%= f.label :arrival_date %>
    <%= f.date_field :arrival_date %>
  </div>

  <div class="form-group">
    <%= f.label :departure_date %>
    <%= f.date_field :departure_date %>
  </div>

  <div class="form-group">
    <%= f.submit "New Trip!" %>
  </div>


  <% end %>
  </div>
</div>

app/views/calendars/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      #map {
        height: 400px;
        width: 50%;
       }
    </style>
  </head>
  <body>

    <div class="container1">
      <div id="column2">
    <div id="map"></div>
    <script>
    function initMap() {
      var destination = {lat: <%= @calendar.destination.latitude %> , lng: <%= @calendar.destination.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 4,
        center: destination
      });
      var marker = new google.maps.Marker({
        position: destination,
        map: map
      });
    }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlFfN3j68LOw1bsZwi62WyOons6y3KZ9Q&callback=initMap">
    </script>
  </body>
</html>
</div>


<div id="column3">
  <div class="container2">
    <h2>Matches</h2>

    <% @current_user.calendars.each do |calendar| %>

      <% calendar.matches.each do |match| %>
      <h4><%= match.destination.name %></h1>
      <h5>User: <%= match.user.email %></h5>
      <h5>Arrival date: <%= match.arrival_date %></h5>
      <h5>Departure date: <%= match.departure_date %></h5>

    <% end %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">

      <nav>
        <%= link_to 'Home', root_path %>
          <% if @current_user.present? %>
            <%= link_to "Sign out #{ @current_user.email }", login_path, :method => 'delete' %>
            <%= link_to 'New Trip', new_calendar_path %>

          <% else %>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign In', login_path %>

      <% end %>
      </nav>

    <%= yield %>
    </div>

  <div style="background-image:url('http://www.3a-travel.com/images/PlaneBackground2.jpg');">

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div id="column4">
  <h1>TravelMate</h1>


  <% if @current_user.present? %>
    Welcome back <%= @current_user.email %>
      <% else %>
    <h3>The match making app for travellers</h3>
  <% end %>


  <br></br>
  </div>
</div>

app/views/session/new.html.erb
<h1>Log in</h1>

<h2><%= flash[:error] %></h2>

  <div class="container">
    <div id="column1">

  <%= form_tag login_path do %>

  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>

  <div class="checkbox">
      <label><input type="checkbox"> Remember me</label>
  </div>

  <div class="form-group">
    <%= submit_tag "Log in" %>
  </div>

  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Join TravelMate</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg.capitalize %></li>
    <% end %>
  </ol>
<% end %>

<div class="container">
  <div id="column1">

  <%= form_for @user do |f| %>

  <div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :class => "form-control", :required => true %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Join!" %>
    </div>

    <% end %>
  </div>
  </div>
</div>